services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/nginx/dockerfile
    container_name: ${CONTENEDOR}
    ports:
      - "${PORT_WEB}:80"     
    env_file:
      - ./.env
    image: ${IMAGEN}/nginx
    volumes:
      - ../../pproyecto/dist:/var/www/html
      - ./logs:/root/logs      
    networks:
      netnginx:
        ipv4_address: ${IP}
networks:
  netnginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}